package com.unam.fciencias.urbanincidents.user.service

import com.unam.fciencias.urbanincidents.user.model.CreateUser
import com.unam.fciencias.urbanincidents.user.model.LoginRequest
import com.unam.fciencias.urbanincidents.user.model.User
import com.unam.fciencias.urbanincidents.user.model.UpdateUserRequest
import com.unam.fciencias.urbanincidents.user.model.Name
import com.unam.fciencias.urbanincidents.user.repository.UserRepository
import com.unam.fciencias.urbanincidents.exception.UserAlreadyExistsException
import com.unam.fciencias.urbanincidents.exception.InvalidTokenException
import com.unam.fciencias.urbanincidents.exception.TokenEmptyOrNullException
import com.unam.fciencias.urbanincidents.exception.UserNotFoundException

import org.springframework.stereotype.Service
import org.springframework.http.HttpStatus
import org.springframework.web.server.ResponseStatusException

import java.util.UUID

@Service
class UserService(
    private val userRepository: UserRepository
) {

    /**
     * Creates a new user in the database.
     *
     * @param request The request object containing the user's email and password.
     * @return The saved user with a generated ID.
     */
    fun createUser(request: CreateUser): User {
        if (existsByEmail(request.email)) {
            throw UserAlreadyExistsException(request.email)
        }

        val user = User(
            id = null,  // The ID is null because it will be generated by the database
            name = request.name,
            role = request.role, 
            email = request.email,
            password = request.password,
            token = "", // Initialize the token as an empty string
            incidents = null, 
        )

        return userRepository.save(user)
    }


    /**
     * This method finds a user by email and password, then updates their token to login.
     * @param loginRequest with the fields of mail and password.
     * @return the user updated if is found, otherwise returns null.
     */
    fun loginUser(loginRequest: LoginRequest): User? {
        // Search user
        val user = userRepository.findByEmailAndPassword(
            loginRequest.email,
            loginRequest.password
        )

        if(user == null){
            throw UserNotFoundException()
        }

        // Update token
        val token = UUID.randomUUID().toString()
        userRepository.updateTokenById(user.id.toString(), token)

        // Return user with new token
        val myUser = User(
            id = user.id.toString(),
            name = user.name, 
            role = user.role, 
            email = user.email,
            token = token,
            password = user.password,
            incidents = user.incidents,
        )
        return myUser
    }

    /**
     * This method finds a user by token, then invalidates the token to logout.
     * @param token the token of the user that is closing session.
     * @return true if the user was found.
     */
    fun logoutUser(token: String): Unit {
        val userFound = userRepository.findByToken(token) ?: throw InvalidTokenException(token)
        userRepository.updateTokenById(userFound.id.toString(), "")
    }

    fun updateUserByToken(token: String, updateRequest: UpdateUserRequest): User {
        val user = userRepository.findByToken(token)
            ?: throw InvalidTokenException(token)

        val userId = user.id ?: throw IllegalStateException("User ID should not be null")

        // Si no hay cambios, no hacemos nada
        if (
            updateRequest.email == null &&
            updateRequest.password == null &&
            updateRequest.name == null
        ) return user

        // Validamos si el nuevo email ya está en uso por otro usuario
        updateRequest.email?.let { newEmail ->
            val existingUser = userRepository.findByEmail(newEmail)
            if (existingUser != null && existingUser.id != userId) {
                throw UserAlreadyExistsException(newEmail)
            }
            userRepository.updateEmailById(userId, newEmail)
        }

        updateRequest.password?.let {
            userRepository.updatePasswordById(userId, it)
        }

        updateRequest.name?.let {
            userRepository.updateNameById(userId, it)
        }

        return userRepository.findById(userId)
            .orElseThrow { UserNotFoundException("User not found after update") }
    }



    fun getUser(token: String) : User{
        val user = userRepository.findByToken(token) 
        if(user == null){
            throw InvalidTokenException(token); 
        }    
        return user
    }

    fun existsByEmail(email: String): Boolean = userRepository.findByEmail(email) != null
}
