package com.unam.fciencias.urbanincidents.user.service

import com.unam.fciencias.urbanincidents.user.model.CreateUser
import com.unam.fciencias.urbanincidents.user.model.LoginRequest
import com.unam.fciencias.urbanincidents.user.model.User
import com.unam.fciencias.urbanincidents.user.repository.UserRepository
import com.unam.fciencias.urbanincidents.user.controller.body.UpdateUserRequest
import org.springframework.stereotype.Service
import org.springframework.http.HttpStatus
import org.springframework.web.server.ResponseStatusException
import java.util.UUID

@Service
class UserService(
    private val userRepository: UserRepository
) {

    /**
     * Creates a new user in the database.
     *
     * @param request The request object containing the user's email and password.
     * @return The saved user with a generated ID.
     */
    fun createUser(request: CreateUser): User {
        if(userRepository.findByEmail(request.email) != null){
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "The email is already registered")
        }
        val user = User(
            id = null,  // The ID is null because it will be generated by the database
            email = request.email,
            password = request.password,
            token = ""  // Initialize the token as an empty string
        )
        // Save the user in the database and return the created user
        return userRepository.save(user)
    }


    /**
     * This method finds a user by email and password, then updates their token to login.
     * @param loginRequest with the fields of mail and password.
     * @return the user updated if is found, otherwise returns null.
     */
    fun loginUser(loginRequest: LoginRequest): User? {
        // Search user
        val user = userRepository.findByEmailAndPassword(
            loginRequest.email,
            loginRequest.password
        ) ?: return null
        // Update token
        val token = UUID.randomUUID().toString()
        userRepository.updateTokenById(user.id.toString(), token)
        // Return user with new token
        val myUser = User(
            id = user.id.toString(),
            email = user.email,
            token = token,
            password = user.password
        )
        return myUser
    }

    /**
     * This method finds a user by token, then invalidates the token to logout.
     * @param token the token of the user that is closing session.
     * @return true if the user was found.
     */
    fun logoutUser(token: String): Boolean {
        val userFound = userRepository.findByToken(token);
        if(userFound != null)
            userRepository.updateTokenById(userFound.id.toString(), "")
        return (userFound != null)
    }

    fun updateUserByToken(token: String, updateRequest: UpdateUserRequest): User? {
        // Buscar usuario por token
        val user = userRepository.findByToken(token) ?: return null

        // Actualizar campos específicos usando consultas del repositorio
        if (updateRequest.email != null && user.id != null) {
            userRepository.updateEmailById(user.id, updateRequest.email)
        }

        if (updateRequest.password != null && user.id != null) {
            userRepository.updatePasswordById(user.id, updateRequest.password)
        }

        // Buscar y devolver el usuario actualizado
        return userRepository.findByToken(token)
    }


    fun getUser(token: String?): User {
        if (token.isNullOrBlank()) {
            throw ResponseStatusException(HttpStatus.UNAUTHORIZED, "Token no proporcionado")
        }
        val user = userRepository.findByToken(token) ?: throw ResponseStatusException(HttpStatus.UNAUTHORIZED, "Token inválido")
        return user
    }

}
